version: "3"
services:
  db:
    image: 'postgres:15'
    restart: always
    ports:
      - '5434:5432'
    expose:
      - '5434'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monokrom
    volumes:
      - './backup:/var/lib/postgresql/data'
    networks:
      - postgres_network
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './cache:/bitnami/redis'
networks:
  postgres_network:
    driver: bridge